version: '3'

services:
  api:
    build:
      context: .
      target: final
    ports:
      - "3000:3000"

  db:
    hostname: db
    image: "mysql:8.0.25"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
    - db-data:/var/lib/mysql
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "database"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
